apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: image-push 
  janus-idp.io/tekton: image-push
  backstage.io/kubernetes-id: image-push
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: image-push
resources: 
- application-dev.yaml 
- application-stage.yaml 
- application-prod.yaml  