apiVersion: backstage.io/v1alpha1
kind: Resource
metadata:
  name: image-push-gitops
  description: This is GitOps manifest for image-push   
  links:
    - url: https://www.redhat.com/en/solutions/trusted-software-supply-chain
      title: Trusted Secure Supply Chain 
      icon: dashboard
      type: admin-dashboard
  annotations:    
    argocd/app-name: image-push
    janus-idp.io/tekton: image-push 
    backstage.io/kubernetes-id: image-push 
    backstage.io/techdocs-ref: dir:. 
spec:
  type: gitops
  owner: user:guest 
  lifecycle: experimental
  dependsOn:
    - component:image-push
