apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: image-push
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: image-push 
  name: image-push
spec:
  ports:
  - port: 8081 
    targetPort: 8081 
  selector:
    app.kubernetes.io/instance: image-push 
